Eliminate the need of sudo for mv, virt-customize
The user running qboxes should now have read/write access
to all libvirt pools, otherwise some operations will fail

diff --git a/qboxes b/qboxes
--- a/qboxes
+++ b/qboxes
@@ -723,10 +723,10 @@ clone_cmd() {
 					printf "%smoving %s between pools (%s ==> %s)%s\n" \
 						"$green" "$clone_volume_name" "$template_pool_name" "$clone_pool_name" "$regular"
 
-					sudo mv "$template_pool_path"/"$clone_volume_name" "$clone_pool_path"/
-					sudo_ec=$?
-					if [ $sudo_ec -ne 0 ]; then
-						printf "%soperation failed, mv returned error code %d, terminating now%s\n" "$red" $sudo_ec "$regular"
+					mv "$template_pool_path"/"$clone_volume_name" "$clone_pool_path"/
+					move_ec=$?
+					if [ $move_ec -ne 0 ]; then
+						printf "%soperation failed, mv returned error code %d, terminating now%s\n" "$red" $move_ec "$regular"
 						exit 2
 					fi
 
@@ -749,7 +749,7 @@ clone_cmd() {
 				printf "%ssetting hostname for %s (this may take a while)%s\n" \
 					"$green" "$candidate" "$regular"
 
-				sudo virt-customize --quiet -d "$candidate" --hostname "$candidate"
+				virt-customize --quiet -d "$candidate" --hostname "$candidate"
 				virt_customize_ec=$?
 				if [ $virt_customize_ec -ne 0 ]; then
 					printf "%soperation failed, virt-customize returned error code %d, terminating now%s\n" \
@@ -759,7 +759,7 @@ clone_cmd() {
 
 				printf "%sdeleting SSH host keys from %s (this may take a while)%s\n\n" "$green" "$candidate" "$regular"
 
-				sudo virt-customize --quiet -d "$candidate" \
+				virt-customize --quiet -d "$candidate" \
 					--delete /etc/ssh/ssh_host_dsa_key \
 					--delete /etc/ssh/ssh_host_dsa_key.pub \
 					--delete /etc/ssh/ssh_host_ecdsa_key \
