Sanitize VM names for command annihilate

diff --git a/qboxes b/qboxes
--- a/qboxes
+++ b/qboxes
@@ -158,29 +158,28 @@ is_name_valid() {
 activate_cmd() {
 	LOWEST_NUM_ARGS=1
 	if [ $# -lt $LOWEST_NUM_ARGS ]; then
-		printf "\n${RED}ERROR:${NC} Incorrect number of arguments (I need at least %d)\n\n" $LOWEST_NUM_ARGS
+		printf "\n${RED}Incorrect number of arguments (I need at least %d)${NC}\n\n" $LOWEST_NUM_ARGS
 		show_usage activate
 	fi
 
-	ALL_INACTIVE_VMS=$(virsh list --name --inactive)
-	if [ -z "$ALL_INACTIVE_VMS" ]; then
-		printf "\n${RED}ERROR:${NC} I cannot seem to find a single inactive VM (is LIBVIRT_DEFAULT_URI set?)\n"
+	ALL_INACTIVE_VMs=$(virsh list --name --inactive)
+	if [ -z "$ALL_INACTIVE_VMs" ]; then
+		printf "\n${RED}I cannot seem to find a single inactive VM (is LIBVIRT_DEFAULT_URI set?)${NC}\n\n"
 		show_usage activate
 	fi
 
 	for candidate; do
 		is_name_valid "$candidate"
-		TEST_RESULT="$?"
-		if [ $TEST_RESULT == 0 ]; then
-			printf "${YELLOW}WARNING:${NC} %s is not a valid VM name\n" "$candidate"
+		if [ $? == 0 ]; then
+			printf "${YELLOW}%s is not a valid VM name${NC}\n" "$candidate"
 		else
-			VM_EXISTS=$(echo "$ALL_INACTIVE_VMS" | grep -w "$candidate")
-			if [ -z "$VM_EXISTS" ]; then
-				printf "${YELLOW}WARNING:${NC} %s is not an inactive VM\n" "$candidate"
+			isInactive=$(echo "$ALL_INACTIVE_VMs" | grep -w "$candidate")
+			if [ -z "$isInactive" ]; then
+				printf "${YELLOW}%s does not look like an inactive VM${NC}\n" "$candidate"
 			else
-				printf "${GREEN}INFO:${NC} Powering inactive VM %s up\n" "$candidate"
-				virsh --quiet start "$candidate" || printf "${RED}ERROR:${NC} Operation failed, virsh returned error code %d\n" $?
-				sleep 1
+				printf "${GREEN}Powering up %s${NC}\n" "$candidate"
+				virsh --quiet start "$candidate" \
+                || printf "${RED}Operation failed, virsh returned error code %d${NC}\n" $?
             fi
 		fi
 	done
@@ -189,45 +188,48 @@ activate_cmd() {
 annihilate_cmd() {
 	LOWEST_NUM_ARGS=1
 	if [ $# -lt $LOWEST_NUM_ARGS ]; then
-		printf "\n${RED}ERROR:${NC} Incorrect number of arguments (I need at least $LOWEST_NUM_ARGS)\n\n"
+		printf "\n${RED}Incorrect number of arguments (I need at least %d)${NC}\n\n" $LOWEST_NUM_ARGS
 		show_usage annihilate
 	fi
-	ALL_INACTIVE_VMS=$(virsh list --name --inactive)
-	if [ -z "$ALL_INACTIVE_VMS" ]; then
-		printf "\n${RED}ERROR:${NC} I cannot seem to find a single inactive VM (is LIBVIRT_DEFAULT_URI set?)\n"
+
+	ALL_INACTIVE_VMs=$(virsh list --name --inactive)
+	if [ -z "$ALL_INACTIVE_VMs" ]; then
+		printf "\n${RED}I cannot seem to find a single inactive VM (is LIBVIRT_DEFAULT_URI set?)${NC}\n\n"
 		show_usage annihilate
 	fi
-	VMs_ANNIHILATED=0
+
 	for candidate; do
-		VM_EXISTS=$(echo "$ALL_INACTIVE_VMS" | grep -w "$candidate")
-		if [ -z "$VM_EXISTS" ]; then
-			printf "${YELLOW}WARNING:${NC} $candidate is not an inactive VM\n"
-		else
-			printf "${GREEN}INFO:${NC} Annihilating ${candidate} (this may take a while)\n"
-			ALL_SNAPSHOTS=$(virsh snapshot-list --name "$candidate")
-			if [ -n "$ALL_SNAPSHOTS" ]; then
-				for each_snapshot in "$ALL_SNAPSHOTS"; do
-				
-					virsh --quiet snapshot-delete --domain "$candidate" --snapshotname "$each_snapshot"
+        is_name_valid "$candidate"
+        if [ $? == 0 ]; then
+            printf "${YELLOW}%s is not a valid VM name${NC}\n" "$candidate"
+        else
+            isInactive=$(echo "$ALL_INACTIVE_VMs" | grep -w "$candidate")
+            if [ -z "$isInactive" ]; then
+                printf "${YELLOW}%s does not look like an inactive VM${NC}\n" "$candidate"
+            else
+                printf "${GREEN}Annihilating %s (this may take a while)${NC}\n" "$candidate"
+                ALL_SNAPSHOTS=$(virsh snapshot-list --name "$candidate")
+                if [ -n "$ALL_SNAPSHOTS" ]; then
+                    for each_snapshot in "$ALL_SNAPSHOTS"; do
 
-					VIRSH_ERROR_CODE="$?"
-					if [ $VIRSH_ERROR_CODE -ne 0 ]; then
-						printf "${RED}ERROR:${NC} Failed to delete snapshot ${each_snapshot} of ${candidate}, virsh returned error code $VIRSH_ERROR_CODE, terminating now.\n"
-						exit 2
-					fi
-				done
-			fi
-			virsh --quiet undefine "$candidate" --remove-all-storage --wipe-storage
+                        virsh --quiet snapshot-delete --domain "$candidate" --snapshotname "$each_snapshot"
 
-			VIRSH_ERROR_CODE="$?"
-			if [ $VIRSH_ERROR_CODE -ne 0 ]; then
-				printf "${RED}ERROR:${NC} Operation failed, virsh returned error code $VIRSH_ERROR_CODE, terminating now.\n"
-				exit 2
-			fi
-			VMs_ANNIHILATED=$((VMs_ANNIHILATED + 1))
-		fi
+                        if [ $? -ne 0 ]; then
+                            printf "${RED}Failed to delete snapshot %s of %s, virsh returned error code %d, terminating now.${NC}\n" "$each_snapshot" "$candidate" $?
+                            exit 2
+                        fi
+                    done
+                fi
+
+                virsh --quiet undefine "$candidate" --remove-all-storage --wipe-storage
+
+                if [ $? -ne 0 ]; then
+                    printf "${RED}Operation failed, virsh returned error code %d, terminating now.${NC}\n" $?
+                    exit 2
+                fi
+            fi
+        fi
 	done
-	printf "${GREEN}SUMMARY:${NC} $VMs_ANNIHILATED VM(s) successfully annihilated.\n"
 }
 
 attach_cmd() {
